name = "OrderedBinning"
uuid = "7ddfbc40-471f-4c10-8de2-c2a38c92fc06"
authors = ["Tamás K. Papp <tkpapp@gmail.com>"]
version = "0.2.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
ArgCheck = "1, 2"
DocStringExtensions = "0.8, 0.9"
julia = "1.8"
